version: '2'

services:
  mountebank:
    image: andyrbell/mountebank
    command: mb --allowInjection --configfile /testapi/apis.ejs
    volumes:
      - ./testapi:/testapi:ro
    ports:
      - 2525:2525
      - 8273:8273
