[tool.black]
line-length = 80
py36 = true
exclude = '''
/(
  | \.circleci
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | atest
  | build
  | dist
  | docker
  | docs
  | results
  | testapi
x)/
'''

[tool.pytest]
testpaths = "test"
addopts = "--cov --spec --instafail --diff-type=auto"
