version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Make: test build install atest
          command: make

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/
          destination: robot-results/

workflows:
  version: 2
  rfdocker:
    jobs:
      - build
