version: 2

jobs:
  atest:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: make install atest
          command: make install atest

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

  all_github:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: upgrade pip
          command: pip install --no-cache-dir --upgrade pip

      - run:
          name: make black test docs build install atest
          command: make all_github

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

  all_prepypi:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: make build publish_pre install_pre atest
          command: make all_prepypi

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

  all_pypi:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: make build publish_prod install_prod atest
          command: make all_pypi

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

workflows:
  version: 2
  make:
    jobs:
      - atest
