version: 2

jobs:
  all_github:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: make black test docs build install atest
          command: make all_github

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

  all_prepypi:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: make publish_pre install_pre atest
          command: make all_prepypi

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

  all_pypi:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: make publish_prod install_prod atest
          command: make all_pypi

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/

workflows:
  version: 2
  make:
    jobs:
      - all_github
