version: 2

jobs:
  make:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Install from source
          command: make install

      - run:
          name: Run acceptance tests
          command: make atest

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/
          destination: robot-results/

workflows:
  version: 2
  build:
    jobs:
      - make
